Update README.md: Backlinks are now built into Silverbullet
Willyfrog/silverbullet-backlinks pull request #8
Opened 2023-11-02 21:10 UTC by johnlunney

2023-11-02 22:21 UTC, Willyfrog requested changes

2023-11-02 22:21 UTC, Willyfrog commented on README.md
> +**UPDATE:** Backlinks functionality is [now built into Silverbullet]([url](https://github.com/silverbulletmd/silverbullet/blob/main/website/CHANGELOG.md#050)).
Should `[url]` be there?

2023-11-02 22:23 UTC, johnlunney commented on README.md
> +**UPDATE:** Backlinks functionality is [now built into Silverbullet]([url](https://github.com/silverbulletmd/silverbullet/blob/main/website/CHANGELOG.md#050)).
No :)

2023-11-03 15:43 UTC, Willyfrog approved these changes
Thanks for the PR! 🚀

2023-11-03 15:43 UTC, merged